package dk.jnie.example.mappers;

import dk.jnie.example.domain.model.DomainRequest;
import dk.jnie.example.domain.model.DomainResponse;
import dk.jnie.example.rest.mappers.RestMapper;
import dk.jnie.example.rest.mappers.RestMapperImpl;
import dk.jnie.example.rest.model.RequestDto;
import dk.jnie.example.rest.model.ResponseDto;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Unit tests for RestMapper.
 * Tests the mapping between REST DTOs and domain objects.
 * Note: MapStruct generates implementation at compile time, so this test verifies the mapping contract.
 */
@DisplayName("RestMapper Tests")
class RestMapperTest {

    private RestMapper restMapper;

    @BeforeEach
    void setUp() {
        // The implementation is generated by MapStruct during compilation
        // This test assumes the generated mapper will be available
        restMapper = new RestMapperImpl();
    }

    @Test
    @DisplayName("requestDTOToDomain maps please to question")
    void requestDTOToDomain_MapsPleaseToQuestion() {
        // Arrange
        RequestDto requestDto = new RequestDto();
        requestDto.setPlease("Give me advice");

        // Act
        DomainRequest result = restMapper.requestDTOToDomain(requestDto);

        // Assert
        assertThat(result).isNotNull();
        assertThat(result.getQuestion()).isEqualTo("Give me advice");
    }

    @Test
    @DisplayName("requestDTOToDomain handles null input")
    void requestDTOToDomain_HandlesNullInput() {
        // Act
        DomainRequest result = restMapper.requestDTOToDomain(null);

        // Assert
        assertThat(result).isNull();
    }

    @Test
    @DisplayName("domainToResponseDto maps answer to advice")
    void domainToResponseDto_MapsAnswerToAdvice() {
        // Arrange
        DomainResponse domainResponse = DomainResponse.builder()
                .answer("Don't worry, be happy!")
                .build();

        // Act
        ResponseDto result = restMapper.domainToResponseDto(domainResponse);

        // Assert
        assertThat(result).isNotNull();
        assertThat(result.getAdvice()).isEqualTo("Don't worry, be happy!");
    }

    @Test
    @DisplayName("domainToResponseDto handles null input")
    void domainToResponseDto_HandlesNullInput() {
        // Act
        ResponseDto result = restMapper.domainToResponseDto(null);

        // Assert
        assertThat(result).isNull();
    }
}
