mma:
  outbound:
    advice-slip-api:
      url: "https://api.adviceslip.com"

micronaut:
  application:
    name: multi-module-micronaut
  server:
    port: 8080
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui-res:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

endpoints:
  health:
    enabled: true
    sensitive: false